name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate-github-contribution-grid-snake

    steps:
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Fiddy2112
          outputs: |
                  dist/github-contribution-grid-snake.svg?palette=github-dark&color_snake=39FF14&color_dots=0f766e,065f46,0e7490,0891b2
                  dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=39FF14&color_dots=0f766e,065f46,0e7490,0891b2
      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
